Update NEMO KGOs with O2 flag

diff --git a/.github/workflows/nemo_tests.yml b/.github/workflows/nemo_tests.yml
--- a/.github/workflows/nemo_tests.yml
+++ b/.github/workflows/nemo_tests.yml
@@ -108,17 +108,16 @@ jobs:
         module load perl/${PERL_VERSION}
         make clean
         export NEMOV4=1  # Enables specific NEMOV4 exclusions in the PSyclone transformation script
-        nvfortran --version
         make -j 4 openmp_gpu
-        make -j 1 compile-openmp_gpu
+        make -j 4 compile-openmp_gpu
         export NV_ACC_POOL_THRESHOLD=75
         make run-openmp_gpu |& tee output.txt
         # Check the output is as expected (TODO #2895: improve numerical reproducibility)
         tail -n 1 output.txt | grep -q " it :      10"  || (echo "Error: 'it :      10' not found!" & false)
-        tail -n 1 output.txt | grep -q "|ssh|_max:  0.25948" || (echo "Error: '|ssh|_max:  0.25948' not found!" & false)
-        tail -n 1 output.txt | grep -q "|U|_max:  0.45851" || (echo "Error: '|U|_max:  0.45851' not found!" & false)
-        tail -n 1 output.txt | grep -q "S_min:  0.48268" || (echo "Error: 'S_min:  0.48268' not found!" & false)
-        tail -n 1 output.txt | grep -q "S_max:  0.40762" || (echo "Error: 'S_max:  0.40762' not found!" & false)
+        tail -n 1 output.txt | grep -q "|ssh|_max:  0.259483" || (echo "Error: '|ssh|_max:  0.259483' not found!" & false)
+        tail -n 1 output.txt | grep -q "|U|_max:  0.458515" || (echo "Error: '|U|_max:  0.458515' not found!" & false)
+        tail -n 1 output.txt | grep -q "S_min:  0.482686" || (echo "Error: 'S_min:  0.482686' not found!" & false)
+        tail -n 1 output.txt | grep -q "S_max:  0.407622" || (echo "Error: 'S_max:  0.407622' not found!" & false)
         export VAR_TIME=$(grep -A 1 "Elapsed Time" output.txt | head -n 2 | tail -n 1 | awk '{print $1}')
         echo $GITHUB_REF_NAME $GITHUB_SHA $VAR_TIME >> ${HOME}/store_results/performance_history_openmp_gpu
         ${HOME}/mongosh-2.1.1-linux-x64/bin/mongosh \
