Revert previous check filename change

diff --git a/.github/workflows/nemo_tests.yml b/.github/workflows/nemo_tests.yml
--- a/.github/workflows/nemo_tests.yml
+++ b/.github/workflows/nemo_tests.yml
@@ -113,11 +113,11 @@ jobs:
         export NV_ACC_POOL_THRESHOLD=75
         make run-openmp_gpu |& tee output.txt  # Here tee is fine because if make fails the next command will too
         # Check the output is as expected (TODO #2895: improve numerical reproducibility)
-        tail -n 1 run.stat | grep -q " it :      10"  || (echo "Error: 'it :      10' not found!" & false)
-        tail -n 1 run.stat | grep -q "|ssh|_max:  0.259483" || (echo "Error: '|ssh|_max:  0.259483' not found!" & false)
-        tail -n 1 run.stat | grep -q "|U|_max:  0.458515" || (echo "Error: '|U|_max:  0.458515' not found!" & false)
-        tail -n 1 run.stat | grep -q "S_min:  0.482686" || (echo "Error: 'S_min:  0.482686' not found!" & false)
-        tail -n 1 run.stat | grep -q "S_max:  0.407622" || (echo "Error: 'S_max:  0.407622' not found!" & false)
+        tail -n 1 output.txt | grep -q " it :      10"  || (echo "Error: 'it :      10' not found!" & false)
+        tail -n 1 output.txt | grep -q "|ssh|_max:  0.259483" || (echo "Error: '|ssh|_max:  0.259483' not found!" & false)
+        tail -n 1 output.txt | grep -q "|U|_max:  0.458515" || (echo "Error: '|U|_max:  0.458515' not found!" & false)
+        tail -n 1 output.txt | grep -q "S_min:  0.482686" || (echo "Error: 'S_min:  0.482686' not found!" & false)
+        tail -n 1 output.txt | grep -q "S_max:  0.407622" || (echo "Error: 'S_max:  0.407622' not found!" & false)
         export VAR_TIME=$(grep -A 1 "Elapsed Time" output.txt | head -n 2 | tail -n 1 | awk '{print $1}')
         ${HOME}/mongosh-2.1.1-linux-x64/bin/mongosh \
           "mongodb+srv://cluster0.x8ncpxi.mongodb.net/PerformanceMonitoring" \
